version: '3'

networks:
  monitor-net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    # restart: unless-stopped
    links:
      - "pushgateway:pushgateway"
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  node:
    container_name: golem_node
    image: aabrioux/golem-node:latest
    restart: always
    networks:
      - monitor-net
    links:
      - "pushgateway:pushgateway"
    environment:
      - YAGNA_METRICS_URL=${YAGNA_METRICS_URL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data-node/ya-provider/:/root/.local/share/ya-provider/
      - ./data-node/yagna/:/root/.local/share/yagna/
    devices:
      - /dev/kvm:/dev/kvm
